language: scala
scala:
  - 2.10.1
node_js:
  - 0.8
jdk:
  - oraclejdk7
  - openjdk7
  
before_install:
  - git submodule update --init --recursive

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g karma
  - npm install --quiet -g karma-firefox-launcher
  - npm install --quiet -g karma-ng-scenario
  - ./pissalot-angular/scripts/web-server.js > /dev/null &
  - sleep 1 # give server time to start

script:
  - cd pissalot-rest
  - sbt ++$TRAVIS_SCALA_VERSION test
  - cd ../pissalot-angular
  - karma start config/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
# Don't use e2e tests for now, don't seem to work on TravisCI
#  - karma start config/karma-e2e.conf.js --reporters=dots --browsers=Firefox
